name: npl
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.10.6
  - pip=22.1.2
  - pandas=1.4.4
  - pytest=6.2.5
  - jax=0.3.17
  - jaxlib=0.3.15
  - scikit-learn=1.1.2
  - scipy=1.9.1 
  - seaborn=0.11.2
  - tqdm=4.64.1
  - pot=0.8.2
  - matplotlib=3.5.3
  - numpy=1.23.2
  - pip:
    - pre-commit==2.20.0