name: npl
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.10
  - pip=22.1.2
  - pytest=6.2.5
  - numpy=1.23.2 
  - jax=0.3.17
  - scipy=1.9.1 
  - seaborn=0.11.2
  - pip:
    - pre-commit==2.20.0